### ISSUE TITLE
regex does not search for what is indicated in comment

### ISSUE THREAD

**Issue by wellhausen** [activeprospect/generator-leadconduit-integration#2]
// regex for either "git://github.com/(user)/(repo).git ..." or "git@github.com:(user)/(repo).git ..."
var match = githubRepoUrl.match(/git[@:]\/*github.com[:/]([^/]+)\/([a-z0-9-_.]+).git/i);

Here is a regular expression that will parse either git://github.com/(user)/(repo).git`or`git@github.com:(user)/(repo).git from the variable githubRepoUrl:

(git@github.com:[a-z0-9-_.]+\/[a-z0-9-_.]+.git)|(git:\/\/github.com\/[a-z0-9-_.]+\/[a-z0-9-_.]+.git)

**Comment by alexkwolfe** [comment]
What is that second format used for? `git://github.com`

**Comment by wellhausen** [comment]
It's used for: git://github.com/(user)/(repo).git

Here's a test: 

var case1 = 'git://github.com/user/repo.git';

var case2 = 'git@github.com:user/repo.git';

var case3 = 'www.google.com';

var regex = new RegExp('(git@github.com:[a-z0-9-_.]+\/[a-z0-9-_.]+.git)|(git:\/\/github.com\/[a-z0-9-_.]+\/[a-z0-9-_.]+.git)');

regex.test(case1); //true

regex.test(case2); //true

regex.test(case3); //false

**Comment by alexkwolfe** [comment]
When would you use the `git://` URL instead of the `git@` URL?

**Comment by wellhausen** [comment]
If this line: var githubRepoUrl = shell.exec('git remote -v', { silent: true }).output.split('\t')[1]; returns that format, as indicated in the comment in line 273. If it does not return that format, 'git@github.com:[a-z0-9-.]+\/[a-z0-9-.]+.git' will work.

**Comment by alexkwolfe** [comment]
Let me ask another way: How did you get the `git://` URL format in your remote configuration? When you create a new repo, the GitHub instructions look like the image below. There's no mention of `git://` anything, so I'm wondering how folks are getting that URL.

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/569/4795037/2c4602b2-5df9-11e4-8804-6bf9b2dbcd0c.png)

**Comment by alexkwolfe** [comment]
Can you run `git remote -v` and paste the output?

**Comment by cgrayson** [comment]
It was Travis. When the tests are run, I saw that URI format in debug output on the CI side.

**Comment by wellhausen** [comment]
This is what I receive: 

origin  https://github.com/ros3bud/leadconduit-integration-requestBin1.git (fetch)
origin  https://github.com/ros3bud/leadconduit-integration-requestBin1.git (push)

Also when creating a new repo, the remote looks different than yours: 
![screenshot 2014-10-27 11 53 16](https://cloud.githubusercontent.com/assets/3402403/4795132/e214a792-5df9-11e4-98fe-3823a0ba6d30.png)

**Comment by cgrayson** [comment]
Namely, [here](https://travis-ci.org/activeprospect/generator-leadconduit-integration/builds/37867932).

> leadconduit:app
> ✓ the generator can be required without throwing (828ms)
> outbound
> No user/repo match in 'git://github.com/activeprospect/generator-leadconduit-integration.git (fetch) origin'
> info Removing dir

**Comment by alexkwolfe** [comment]
Huh. Still no clue why it's that format, but I guess it doesn't matter. 

The match groups in the regex you provided, @ros3bud, are incorrect. Why doesn't the current regex work as expected?

**Comment by wellhausen** [comment]
var case2 = 'git@github.com:user/repo.git';
var regex1 = new RegExp('/git[@:]\/*github.com[:/]([^/]+)\/([a-z0-9-_.]+).git/i');
regex1.test(case2); this gives me a false and I would expect that to be true if it were working.

**Comment by alexkwolfe** [comment]
Why doesn't it work?

**Comment by wellhausen** [comment]
It looks like the regex is expecting slashes after 'com:' and before user, rather than between 'user' and 'repo'.
