### ISSUE TITLE
Should generate sample validate() for outbound

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/generator-leadconduit-integration#5]
The LeadConduit handler is adding support for a `validate()` function on an integration, to verify essential data is present before making the request (e.g., [Telesign shouldn't be called if there's no phone number](https://github.com/activeprospect/leadconduit-integration-telesign/commit/39a4f3647e0c960f911506d625477cc572187c7f)). An example of this should be added to generated outbound code.

**Comment by alexkwolfe** [comment]
Shall I take this one?

**Comment by cgrayson** [comment]
Not sure it's top priority today, but you can if you want.
