### ISSUE TITLE
add standard helpers?

### ISSUE THREAD

**Issue by zalary** [activeprospect/generator-leadconduit-integration#7]
it seems that often when I build an integration, I'm looking for ways to parse integers and prices and etc in a way that doesn't break or return NaN.   seems like we might be able to build a standard helper file to help guide newbies and oldbies alike.

**Comment by cgrayson** [comment]
As discussed offline, moved to [integration issue #1](https://github.com/activeprospect/leadconduit-integration/issues/1).
